### PR TITLE
Create fast interface to tries for untyped code.

### PR DESCRIPTION
**Pull request by samth**

### CODE REVIEW

**Comment by samth** [comment]
This address the problem pointed out by @jbclements. The following test case runs much much faster:

```
#lang racket

(require pfds/trie)
(require (prefix-in f: pfds/trie-untyped))

(define (rand-list)
    (for/list ([i (in-range 128)])
          (random 256)))

(define t (trie (list (rand-list))))
(define u (time (bind (rand-list) 0 t)))

(define t* (f:trie (list (rand-list))))
(define u* (time (f:bind (rand-list) 0 t)))
```

**Comment by samth** [comment]
Note that this has no documentation yet, and thus isn't quite suitable for merging.

**Comment by takikawa** [comment]
I'll just merge this and add untyped versions of the others too along with docs. I think I like the convention of doing `pfds/foo/untyped` for each `foo`, so I'll restructure it like that.

**Comment by samth** [comment]
Not as good as #9.

**Pull request closed without merging**
